#+TODO: TODO PENDING | DONE DECLINED AWARDED EXPIRED
#+TEMPLATE: NSF Proposal - Current and pending
#+key: nsf-proposal-current-and-pending
#+group: proposal
#+contributor: John Kitchin <jkitchin@andrew.cmu.edu>
#+default-filename: current-and-pending.org

#+LATEX_CLASS: cmu-article
#+LATEX_CLASS_OPTIONS: [12pt]
#+LATEX_HEADER: \usepackage[usenames, dvipsnames]{color}
#+OPTIONS: toc:nil
#+TITLE: Current and Pending
\maketitle

# Directions: Add your proposals to [[*Proposals]].
# Then export the document elisp:ox-manuscript-export-and-build-and-open
# See [[*Code to generate C&P]] if you need a different template to format the entries.

# Do not delete this line. The C&P goes here.
#+RESULTS: current-and-pending

* Proposals				:noexport:
List your proposals here as subheadings. The subheading title is the title of the proposal. You should define the following properties on the heading:
- AGENCY :: the funding agency
- ROLE :: Your role in the proposal (PI, co-PI, senior personnel)
- PI :: The name
- AMOUNT :: total amount of the grant in dollars
- PERSON-MONTHS :: The number of months per year you are paid from the grant
- START-DATE :: When the grant starts
- DURATION :: in years

** AWARDED Multifunctional Oxygen Evolution Electrocatalyst Design and Synthesis
  :PROPERTIES:
  :AGENCY:   DOE-BES
  :ROLE:     PI
  :AMOUNT:   $750,000
  :START-DATE: [2010-01-01 Fri]
  :DURATION: 5 years
  :PERSON-MONTHS: 1 summer
  :END:

** AWARDED Systems Analysis of Advanced Power Plant Carbon Capture Technologies
   :PROPERTIES:
   :AMOUNT:   $507,000
   :ROLE:     senior personnel
   :START-DATE: [2012-11-15 Thu]
   :END_DATE: [2015-11-14 Sat]
   :DURATION: 3 years
   :PERSON-MONTHS: 0.25 summer
   :END:

** AWARDED TechELA: Improving education and research
   CLOSED: [2014-03-31 Mon 19:04] DEADLINE: <2014-03-31 Mon -1m>
   :PROPERTIES:
   :AMOUNT:   $20,000
   :AGENCY:   Carnegie Mellon University
   :ROLE:     PI
   :START-DATE: [2014-06-15 Sun]
   :END-DATE: [2016-06-15 Wed]
   :PERSON-MONTHS: 0.1
   :DURATION: 2 years
   :END:

** AWARDED Modeling bulk composition dependent alloy surface properties under reaction conditions
   CLOSED: [2015-06-02 Tue 13:45]
   :PROPERTIES:
   :AGENCY:   NSF CBET
   :ROLE:     PI
   :AMOUNT:   $374,263
   :PERSON-MONTHS: 1 summer
   :START-DATE: [2015-08-01 Sat]
   :DURATION: 3 years
   :END:

** AWARDED Advanced Manufacturing To Enable Enhanced Processes And New Solvents For Carbon Capture
   CLOSED: [2015-06-02 Tue 13:45]
   :PROPERTIES:
   :AGENCY:   NETL
   :ROLE:     PI
   :PERSON-MONTHS: 1 summer
   :START-DATE: [2016-06-01 Wed]
   :DURATION: 3 years
   :AMOUNT:   $100,000
   :END:

** PENDING Modeling low-dimensional alloy phase behavior using density functional theory and machine learning
  :PROPERTIES:
  :AGENCY:   ACS Petroleum Research Foundation
  :ROLE:     PI
  :PERSON-MONTHS: 1 summer
  :START-DATE: <2016-06-01 Wed>
  :DURATION: 2 years
  :AMOUNT:   $100,000
  :END:

** PENDING EAGER Germination: Transformative idea development through writing
  :PROPERTIES:
  :AMOUNT:   $32,119
  :AGENCY:   NSF
  :ROLE:     PI
  :PERSON-MONTHS: 1 summer
  :START-DATE: [2016-06-01 Wed]
  :DURATION: 1 year
  :END:

** PENDING DMREF: Collaborative Research: Accelerated design-discovery of dimensionally stabilized alloy nanoparticle phases
   :PROPERTIES:
   :AMOUNT:   $1.2M
   :AGENCY:   NSF
   :ROLE:     co-PI
   :PERSON-MONTHS: 1 summer
   :START-DATE: [2016-06-01 Wed]
   :DURATION: 3 years
   :END:


* Code to generate C&P			:noexport:
  :PROPERTIES:
  :ID:       770B3E21-5CE6-4641-99E4-061058853D7F
  :END:
This section contains the code that generates the current and pending text. You can run this code and it will put the

#+name: current-and-pending
#+BEGIN_SRC emacs-lisp :results drawer
(setq c-and-p-template
      "@@latex:\\parbox{\\textwidth}{%@@
\\noindent
*Title:* ${title} \\\\
,*Agency*: ${AGENCY} \\\\
,*Role*: ${ROLE} \\\\
,*Status*: ${status}  \\\\
,*Total amount of award*: ${AMOUNT}  \\\\
,*Start date*: ${START-DATE} (${DURATION}) \\\\
,*Devoted person-months*: ${PERSON-MONTHS} \\\\
,*Relevance to this proposal:* ${body}@@latex:}@@
\\\\
\\\\
")


(defun c-and-p-formatter (variable)
  (or
   (cond
    ((string= variable "title")
     (nth 4 (org-heading-components)))
    ((string= variable "status")
     (let ((status (nth 2 (org-heading-components))))
       (cond
	((string= status "AWARDED")
	 "\\textcolor{ForestGreen}{Awarded}")
	((string= status "PENDING")
	 "\\textcolor{orange}{Pending}"))))

    ;; Body of section
    ((string= variable "body")
     (save-restriction
       (org-narrow-to-subtree)
       (org-end-of-meta-data-and-drawers)
       (buffer-substring (point) (point-max))))
    ;; Get a property
    (t
     (org-entry-get (point) variable)))
   ""))

(mapconcat 'identity (org-map-entries
 (lambda ()
   (s-format c-and-p-template 'c-and-p-formatter))
 "TODO=\"PENDING\"|TODO=\"AWARDED\"")
"\n\n")
#+END_SRC
* Local variables			:noexport:
This makes it possible to just export this file to get the current and pending.
# Local Variables:
# org-export-babel-evaluate: t
# End:
