#+TEMPLATE: NSF Proposal - postdoctoral mentoring plan
#+key: nsf-proposal-postdoc-plan
#+group: proposal
#+contributor: John Kitchin <jkitchin@andrew.cmu.edu>
#+default-filename: postdoctoral-mentoring-plan.org

#+LATEX_CLASS: cmu-article
#+Latex_class_options: [12pt]
#+OPTIONS: toc:nil ^:{}
#+LATEX_HEADER: \usepackage{setspace}

# Adjust this to fill the page. 1.0 is single line spacing.
\setstretch{1.2}

# Link in GPG http://www.nsf.gov/pubs/policydocs/pappguide/nsf14001/gpg_2.jsp#IIC2j
# adapted from https://engineering.cmu.edu/faculty_staff/services/research_resources/rasc/documents/nsf-postdoc-mentoring-plan-template-1.docx

This Postdoctoral Researcher Mentoring Plan has been prepared by Carnegie Mellon University (CMU). The Plan establishes guidelines for work to be performed by a Postdoctoral Researcher (PDR) in the <replace: Insert Department Here> in support of the NSF <replace:[insert program name]> project submitted by CMU, entitled <replace:[Insert “title of project”.]> The PDR assigned to the project will conduct research on <replace:[name tasks]>.

1. Career Counseling will be directed at providing the PDR with the skills, knowledge, and experience needed to excel in his/her chosen career path. In addition to guidance provided by <replace:[Insert Principal Investigator name]>, the PDR will be encouraged to discuss career options with researchers and managers at CMU and with former students and colleagues of <replace:[Insert Principal Investigator name]>.

2. Experience with Preparation of Grant Proposals will be gained by direct involvement of the PDR in proposals prepared by CCMU. The PDR will have an opportunity to learn best practices in proposal preparation including identification of key research questions, definition of objectives, description of approach and rationale, and construction of a work plan, timeline, and budget.

3. Publications and Presentations are expected to result form the work supported by the grant. These will be prepared under the direction of  <replace:[Insert Principal Investigator name]> and in collaboration with researchers at CMU as appropriate. The PDR will receive guidance and training in the preparation of manuscripts for scientific journals and presentations at conferences.

4. Teaching and Mentoring Skills will be developed in the context of regular meetings within CMU research groups, during which graduate students and postdoctoral researchers describe their work to colleagues within the group and assist each other with solutions to challenging research problems, often resulting in cross fertilization of ideas. PDR’s will have full access to CMU’s Eberly Center for Teaching Excellence (http://www.cmu.edu/teaching/eberly).

5. Instruction in Professional Practices will be provided on a regular basis in the context of the research work and will include fundamentals of the scientific method, laboratory safety, and other standards of professional practice. The PDR will be encouraged to affiliate with one or more professional societies in his/her chosen field. Non-native speaking PDR’s will have full access to CMU’s Intercultural Communication Center (http://my.cmu.edu/portal/site/admission/inter_comm/).

6. Effective collaboration with researchers from diverse backgrounds and disciplinary areas is a staple of research at <replace:[Insert Department Name Here]>. PDR’s will have the opportunity to work with researchers from diverse backgrounds and across multiple disciplines in any one of our over two dozen Centers, Labs or affiliated Centers and Institutes. Our research programs also offer interaction with industry through individual faculty sponsors, research center industrial liaison programs, and through departmental advisor boards.

7. Success of the Mentoring Plan will be assessed by monitoring the personal progress of the PDR through a tracking of the PDR’s progress toward his/her career goals after finishing the postdoctoral program.


* Build					:noexport:

   elisp:ox-manuscript-export-and-build-and-open
