#+TEMPLATE: NSF Proposal - Checklist
#+key: nsf-proposal-checklist
#+group: proposal
#+contributor: John Kitchin <jkitchin@andrew.cmu.edu>
#+default-filename: checklist.org

#+TITLE: NSF Proposal Checklist
#+LATEX_CLASS: cmu-article
#+Latex_class_options: [12pt]
#+OPTIONS: toc:nil

NSF Grant Proposal Guide: http://www.nsf.gov/pubs/policydocs/pappguide/nsf14001/index.jsp

# Obviously some of these directions are specific to CMU.
# Provide the following information to Shirley Pavlischak
# <shirleyp@andrew.cmu.edu> to get started:

Proposal Title: <replace: with your title>

Proposal Due Date: <replace: with due date>

Solicitation number: <replace: with number>

NSF Division: <replace: with division/program>

PI: <replace: with name>

Co-PIs: <replace: names or delete>

Start date: <replace: date>

Duration: <replace: duration>

* Checklist [1/12]

- [ ] Budget                       [[http://www.nsf.gov/pubs/policydocs/pappguide/nsf14001/gpg_2.jsp#IIC2g][GPG IIC2g]]
- [ ] [[https://engineering.cmu.edu/faculty_staff/services/research_resources/rasc/documents/budget-justification-template_nsf_11_09_15.docx][Budget Justification]]         see [[id:87FEAFB7-0AAC-48A2-9FA6-87BED951656F][Budget notes]]
- [X] [[elisp:(ox-manuscript-new-manuscript "nsf-sow")][Statement of Work]]            see [[id:87FEAFB7-0AAC-48A2-9FA6-87BED951656F][Budget notes]]
- [ ] SPEX signoff

- [ ] [[elisp:(ox-manuscript-new-manuscript "nsf-proposal-biosketch")][Biographical Sketch]]          [[http://www.nsf.gov/pubs/policydocs/pappguide/nsf14001/gpg_2.jsp#IIC2f][GPG IIC2f]]
- [ ] [[elisp:(ox-manuscript-new-manuscript "nsf-proposal-current-and-pending")][Current and Pending]]          [[http://www.nsf.gov/pubs/policydocs/pappguide/nsf14001/gpg_2.jsp#IIC2g][GPG IIC2g]]
- [ ] [[elisp:(ox-manuscript-new-manuscript "nsf-proposal-facilities")][Facilities]]                   [[http://www.nsf.gov/pubs/policydocs/pappguide/nsf14001/gpg_2.jsp#IIC2g][GPG IIC2g]]

- [ ] [[elisp:(ox-manuscript-new-manuscript "nsf-project-summary")][Project Summary]]              [[http://www.nsf.gov/pubs/policydocs/pappguide/nsf14001/gpg_2.jsp#IIC2b][GPG IIC2b]]
- [ ] [[elisp:(ox-manuscript-new-manuscript "nsf-project-description")][Project Description]]          [[http://www.nsf.gov/pubs/policydocs/pappguide/nsf14001/gpg_2.jsp#IIC2d][GPG IIC2d]]
- [ ] References Cited             [[http://www.nsf.gov/pubs/policydocs/pappguide/nsf14001/gpg_2.jsp#IIC2e][GPG IIC2e]]

- [ ] [[elisp:(ox-manuscript-new-manuscript "nsf-proposal-postdoc-plan")][Postdoctoral Mentoring Plan]]  [[http://www.nsf.gov/pubs/policydocs/pappguide/nsf14001/gpg_2.jsp#IIC2j][GPG IIC2j]]
- [ ] [[elisp:(ox-manuscript-new-manuscript "nsf-proposal-data-plan")][Data Management plan]]         [[http://www.nsf.gov/pubs/policydocs/pappguide/nsf14001/gpg_2.jsp#IIC2j][GPG IIC2j]]



** General resources
RESEARCH ADMINISTRATION SUPPORT CENTER: https://engineering.cmu.edu/faculty_staff/services/research_resources/rasc/proposal-preparation/faculty/index.html

** Budget notes
   :PROPERTIES:
   :ID:       87FEAFB7-0AAC-48A2-9FA6-87BED951656F
   :END:

1.	Work with David DeLo <dd03@andrew.cmu.edu> and Shirley Pavlischak <shirleyp@andrew.cmu.edu>to prepare the budget.
2.	Use the mandatory Budget justification format from the Dean’s office https://engineering.cmu.edu/faculty_staff/services/research_resources/rasc/documents/budget-justification-template_nsf_11_09_15.docx

3.	Provide the Statement of work (brief summary) for OSP
4.	Sign the SPEX form

** Project Summary Notes
(Plain text, 3 sections, 4600 characters)
You must have an Overview, Intellectual Merit and Broader Impacts section. Send this to Shirley in plain text, she will paste it into boxes on FastLane.

** Project Description Notes
Prior NSF support sections must explicitly identify intellectual merit and broader impacts.

** Postdoctoral Mentoring plan template
https://engineering.cmu.edu/faculty_staff/services/research_resources/rasc/documents/nsf-postdoc-mentoring-plan-template-1.docx

** Data Management plan
https://engineering.cmu.edu/faculty_staff/services/research_resources/rasc/documents/nsf-data-management-plan-template-1.docx
  Maximum of two pages

* Build
Refresh all the files with a fresh build.

#+BEGIN_SRC emacs-lisp
(loop for org-file in '("project-description.org"
			"project-summary.org"
			"biosketch.org"
			"current-and-pending.org"
			"data-management-plan.org"
			"facilities.org"
			"postdoctoral-mentoring-plan.org")
      do
      (find-file org-file)
      (ox-manuscript-export-and-build-and-open))
#+END_SRC

* Email the proposal pieces
This  will open an email and attach the relevant pieces of the proposal.

#+BEGIN_SRC emacs-lisp
(compose-mail "Shirley Pavlischak <shirleyp@andrew.cmu.edu>" "NSF Proposal pieces")

(loop for pdf in '("project-description.pdf"
		   "project-description-references.pdf"
		   "project-summary.pdf"
		   "biosketch.pdf"
		   "current-and-pending.pdf"
		   "data-management-plan.pdf"
		   "facilities.pdf"
		   "postdoctoral-mentoring-plan.pdf")
      do
      (mml-attach-file pdf))

(message-goto-body)
(insert "Hi Shirley,
Here are the pieces to my current proposal.

Thanks,")
#+END_SRC

#+RESULTS:
